- spec/fixtures/mods/sbhcmss78_FlyingAStudios_collection.xml
updates encoding from iso8601 to w3cdtf
> updates date encoding attribute of MODS collection record

- Gemfile
- Gemfile.lock
- app/indexers/object_indexer.rb
- config/application.yml
- config/initializers/riiif_initializer.rb
- lib/importer/csv.rb
- lib/importer/factory/object_factory.rb
> DIGREPO-777: generate thumbnails during ingest

- app/views/catalog/_file_sets_list.html.erb
- app/views/catalog/_files.html.erb
This should never actually happen, but when it does, don't 500.
> fix DIGREPO-805

- app/indexers/object_indexer.rb
> DIGREPO-837: fix rights_holder_label for older repo states

- app/controllers/access_controller.rb
- spec/controllers/access_controller_spec.rb
I'll want to do some manual testing first.
> DIGREPO-840

- Rakefile
- config/resque-pool.yml
- lib/importer/cli.rb
- lib/importer/csv.rb
- lib/importer/cylinder.rb
- lib/importer/etd.rb
- lib/importer/factory.rb
- lib/importer/factory/etd_factory.rb
- lib/importer/factory/job.rb
- lib/importer/factory/object_factory.rb
- lib/importer/mods.rb
- lib/object_factory_writer.rb
- spec/lib/importer/csv_spec.rb
- spec/lib/importer/cylinder_spec.rb
- spec/lib/importer/etd_spec.rb
- spec/lib/importer/factory/object_factory_spec.rb
~~Currently only for CSVs, and buggy (multiple copies of a collection are sometimes created).~~
> DIGREPO-843: enable concurrent ingests

- Gemfile
- Gemfile.lock
> [deps] upgrade blacklight_range_limit to 6.2.x

- app/views/catalog/_deep_zoom.html.erb
> views/deep_zoom: guard against documents with no filesets

- app/views/welcome/using.html.erb
> views/welcome/using: add missing periods to TOC links

- config/secrets.yml.template
- config/sru.yml
> SRU: add Alma endpoint to sru.yml

- lib/importer/factory/collection_factory.rb
I'm honestly not sure how this ever worked.
> CollectionFactory: fix #find

- doc/migration.md
Adds initial draft of ADRL migration protocol markdown file. Sorry for the large number of commits -- nested list markdown formatting is finicky.
> Migration protocol

- app/views/welcome/using.html.erb
> FAQ: link to GitHub repo

- config/resque-pool.yml
> resque: back to 1 worker

- app/controllers/catalog_controller.rb
- config/application.yml
- config/secrets.yml.template
Followup to https://github.com/ucsblibrary/alexandria/pull/102
> OAI: namespace settings, move some to application.yml

- config/deploy/demo.rb
Also, remove redundant git uri
Connected to https://github.com/curationexperts/alexandria/issues/8
> Add cap stage for demo environment

- app/models/solr_document.rb
This commit improves the accuracy of the solr
field to DC terms mapping that is used for OAI-PMH
publishing.
> Additional OAI/DC mapping

- app/assets/javascripts/application.js
- app/assets/javascripts/jcarousel.js
- app/assets/javascripts/jquery.jcarousel.js
- app/assets/stylesheets/application.scss
- app/views/catalog/_media_image.html.erb
- app/views/catalog/_media_image.html.erb.rej
- fix newspaper display (deep zoom doesn't work since FITS can't
determine the dimensions for the riiif manifest)
- fix https://github.com/curationexperts/alexandria/issues/78#issuecomment-375061592
> partially revert a21118

- app/indexers/object_indexer.rb
- app/jobs/full_text_to_solr_job.rb
- lib/importer/factory/object_factory.rb
- spec/fixtures/vcr/csv_importer.yml
- spec/jobs/full_text_to_solr_job_spec.rb
- spec/lib/importer/csv_full_text_indexing_spec.rb
Otherwise re-indexing will not update all_text_timv
> move full-text indexing to ObjectIndexer

- app/indexers/object_indexer.rb
> ObjectIndexer: index member_ids to preserve FileSet order

- app/helpers/application_helper.rb
> ApplicationHelper#linkify: fix URI replace regexp

- app/views/welcome/using.html.erb
> FAQ: update Fedora URL

- app/controllers/catalog_controller.rb
> OAI-PMH: export collections as sets

- app/indexers/object_indexer.rb
> ObjectIndexer: add field for normalized accession number

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/indexers/etd_indexer.rb
- app/models/etd.rb
- lib/traject/audio_config.rb
- lib/traject/etd_config.rb
- lib/traject/extract_contributors.rb
- lib/traject/extract_cylinder_contributors.rb
- lib/traject/extract_etd_contributors.rb
- spec/fixtures/proquest/zipped/ETD_ucsb_0035D_13132_MARC.xml
- spec/lib/importer/etd_spec.rb
> ETDs: create local authorities for contributors

- lib/tasks/import.rake
To run on staging 
```
RAILS_ENV=production bundle exec rake 'import:adrl_arks[/opt/alexandria/current/tmp/merritt_proquest.csv, /opt/alexandria/current/tmp/adrl_arks.csv]' --trace
```
> Fixes post staging run of this import:adrl_arks task
